baseURL = 'https://rasa-parayana.art/'
languageCode = 'en-us'
title = 'Rasa Parayana'
copyright = 'Essays on Gaudiya Vaishnava thought and practice.'
theme = 'hello-friend-ng'
defaultContentLanguage = 'en'

enableEmoji = true

[pagination]
pagerSize = 10

[menu]
  [[menu.main]]
    identifier = 'posts'
    name       = 'Posts'
    url        = '/post/'
    weight     = 10

[taxonomies]
  tag      = 'tags'
  category = 'categories'

[params]
  dateform             = 'Jan 2, 2006'
  dateformShort        = 'Jan 2'
  dateformNum          = '2006-01-02'
  dateformNumTime      = '2006-01-02 15:04'
  description          = 'Essays on Gaudiya Vaishnava thought and practice.'
  keywords             = ''
  images               = ['']
  homeSubtitle         = ''
  subtitle             = ''
  themeColor           = '#1b1c1d'
  disableReadOtherPosts = false
  readOtherPosts       = 'Read other posts'
  enableThemeToggle     = true
  enableSharingButtons  = false
  enableReadingTime     = true
  enableGlobalLanguageMenu = false
  customCSS            = ['css/home-intro.css']

  [params.logo]
    logoText     = 'Rasa Parayana'
    logoHomeLink = '/'

  [params.author]
    name = 'Rasa Parayana'

  [params.footer]
    trademark = 2026
    rss       = true
    copyright = true
    author    = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ['HTML', 'RSS']
